version: '3'

services:
  php-server:
    build:
      context: .
      dockerfile: php-server.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./your-php-file.php:/var/www/html/your-php-file.php
    depends_on:
      - neo4j

  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    volumes:
      - ./data/neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - 7474:7474
      - 7687:7687